### ISSUE TITLE
Create Conda environments from environment files

### ISSUE THREAD

**Issue by William-Hill** [ESGF/esgf-ansible#19]
Conda can export the setting of an environment so that the environment can be reproduced.  I've exported the conda environments that got created on an all node type that was installed on cwt-node and will try to integrate the use of the environment file into the ansible script.

**Comment by William-Hill** [comment]
Resolved by #26

**Comment by nathanlcarlson** [comment]
Hi @William-Hill, doesn't #26 solve the issue of having a more reliable source of built components? Where as the task outlined in this issue is related to the creation of conda environments using environment files?

**Comment by William-Hill** [comment]
You're correct @nathanlcarlson.  Totally spaced on this.  Thanks for reopening

**Comment by nathanlcarlson** [comment]
#69 Has been made and may be relevant to this issue.

**Comment by sashakames** [comment]
What might be needed to prepare future environments is a "bleeding edge" mode for the playbook.  Perhaps this resides in a special branch.  The default might have required packages without versions specified.  If the environment won't build, or the resulting components won't run due to package version conflicts or other issues, then we need to dial in some specific component versions.  This would only be needed when we need to prepare an update to the environment when there is one or more specific package updates.  Generally speaking it should be sufficient to simply update the package version in the environment file with all versions explicit.

**Comment by nathanlcarlson** [comment]
Going to close this issue as the conda environments seem to be working much better. We can repoen it or otherwise if this is determined to be a feature we would like.
